### ISSUE TITLE
Could not resolve hostname ml workstation:

### ISSUE THREAD

**Issue by BreakingTheExpectations0** [miccio-dk/machine-learning-workstation-docs#1]
After creating config file (as txt) in the folder ssh (anaconda/lib/python3.7/.../ssh), this is the message error I have:

<img width="1037" alt="Captura de pantalla 2019-10-03 a las 12 18 42" src="https://user-images.githubusercontent.com/22612821/66119514-0e2ced00-e5d9-11e9-8c30-8b2e6c5e5607.png">

**Comment by miccio-dk** [comment]
Hi! the folder you should use is `~/.ssh`. That means, it should be located right inside your home directory, and there must be a dot in front of it.

Try with:
```
mkdir ~/.ssh
nano  ~/.ssh/config
```
